[package]
name = "youtube2mp3Converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5.0"
fltk = "1.4.13"
youtube_dl = "0.9.0"
